// export const ADD_TODO_ITEM = 'ADD_TODO_ITEM';
export const RESET_LIST = 'RESET_LIST';
export const REMOVE_TODO_ITEM = 'REMOVE_TODO_ITEM';
export const SAVE_TODO_START = 'SAVE_TODO_START';
export const SAVE_TODO_ITEM_SUCCESS = 'SAVE_TODO_ITEM_SUCCESS';
export const SAVE_TODO_FAILED = 'SAVE_TODO_FAILED';
export const SAVE_TODO_UNAUTH = 'SAVE_TODO_UNAUTH';

export const FETCH_TODOS_START = 'FETCH_TODOS_START';
export const FETCH_TODOS_SUCCESS = 'FETCH_TODOS_SUCCESS';
export const FETCHED_TODOS_FAILED = ' FETCHED_TODOS_FAILED';
export const REMOVE_TODO= 'REMOVE_TODO';

export const SHOW_ALL_TODOS = 'SHOW_ALL_TODOS';
export const SHOW_ACTIVE_TODOS = 'SHOW_ACTIVE_TODOS';
export const SHOW_COMPLETED_TODOS = 'SHOW_COMPLETED_TODOS';

export const UPDATE_COMPLETED_SUCCESS = 'UPDATE_COMPLETED_SUCCESS';
export const UPDATE_COMPLETED= 'UPDATE_COMPLETED';

export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';